### ISSUE TITLE
docker-compose mysql connection refused

### ISSUE THREAD

**Issue by TikWind** [apache/incubator-apisix-dashboard#302] opened 2020-07-10 06:24 UTC
## Descripe

Hi everyone, I follow https://github.com/apache/incubator-apisix-dashboard/blob/master/compose/README.md to deploy this project, but when I visit http://127.0.0.1/dashboard/ in the browser, it redirect http://127.0.0.1/dashboard/setting :

![image](https://user-images.githubusercontent.com/65604564/87121771-23485200-c2b6-11ea-8569-6f22253ae65f.png)

When I use `docker logs` to look image name "dashboard_manager" and container name "dashboard_manager_1" :

![image](https://user-images.githubusercontent.com/65604564/87122425-71118a00-c2b7-11ea-9578-911e0c939b0b.png)

## Question

There is a error `panic: fail to connect to DB: dial tcp 192.17.5.14:3306: connect: connection refused for root:123456@tcp(192.17.5.14:3306)/manager?charset=utf8&parseTime=True&loc=Local`. Why? How to solve this problem? Thanks. 

## Environment

System: CentOS Linux release 7.8.2003 (Core)
CPU: 4 core
Memory: 8G

**Comment by TikWind** [comment] 2020-07-10 07:18
@juzhiyuan hello, can u help me to have a look? Thanks.

**Comment by juzhiyuan** [comment] 2020-07-10 07:23
Hi, this may be related to a issue we found those days, and it will be fixed this weekend. Once it’s fixed, I will notify you here.

**Comment by TikWind** [comment] 2020-07-10 07:24
OK, thanks. @juzhiyuan

**Comment by juzhiyuan** [comment] 2020-07-13 00:25
Please have a try in the new Dashboard :)

**Comment by imjoey** [comment] 2020-07-13 00:39
+1 for same issue.

@juzhiyuan May I ask which pull request fixed this or what the cause was? Thanks.

**Comment by TikWind** [comment] 2020-07-13 01:02
I hava tried again in master branch, but it is the same. @juzhiyuan

**Comment by juzhiyuan** [comment] 2020-07-13 01:16
@TikWind Hi, would you mind adding my WeChat (JuShaoyao) and have a remote screen share?

@imjoey I will update here once this issue is fixed.

**Comment by imjoey** [comment] 2020-07-13 05:01
@juzhiyuan @TikWind  For your information, the mysql connection error has gone with the latest code and everything worked in my case.

**Comment by juzhiyuan** [comment] 2020-07-13 06:33
ok

**Comment by juzhiyuan** [comment] 2020-07-13 06:33
Feel free to reopen this issue when the error occurred again

**Closed by juzhiyuan** 2020-07-13 06:33 UTC

**Comment by imjoey** [comment] 2020-07-13 08:18
> Feel free to reopen this issue when the error occurred again

@juzhiyuan many thanks.

**Comment by TikWind** [comment] 2020-07-20 01:58
This bug is not mysql connect problem, at the begining, mysql start slowly, so other can' connect(so it will output error logs ), but when mysql start success, it is OK. 

The real problem may be incompatibility problem, #324 #322 can resolve this bug.

**Comment by imjoey** [comment] 2020-07-20 02:03
> This bug is not mysql connect problem, at the begining, mysql start slowly, so other can' connect(so it will output error logs ), but when mysql start success, it is OK.
> 
> The real problem may be incompatibility problem, #322 #324 can resolve this bug.

@TikWind Good catch. Thanks for your work. 

While I have one more question that, everything is fine with my macOS docker desktop environment, is this bug OS dependent? Thanks.
